
package com.movie;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "movie_service", targetNamespace = "http://www.mycom.com/movie")
public interface MovieService {


    /**
     * 
     * @param movie
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.mycom.com/movie/NewOperation")
    @WebResult(name = "status", targetNamespace = "")
    @RequestWrapper(localName = "addMovie", targetNamespace = "http://www.mycom.com/movie", className = "com.movie.AddMovie")
    @ResponseWrapper(localName = "addMovieResponse", targetNamespace = "http://www.mycom.com/movie", className = "com.movie.AddMovieResponse")
    public String addMovie(
        @WebParam(name = "movie", targetNamespace = "")
        MovieType movie);

}
