
package com.movie;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "MovieService", targetNamespace = "http://www.mycom.com/movie", wsdlLocation = "file:/C:/workspace/WebServiceProject/wsdl/movie_service.wsdl")
public class MovieService_Service
    extends Service
{

    private final static URL MOVIESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.movie.MovieService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.movie.MovieService_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/workspace/WebServiceProject/wsdl/movie_service.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/workspace/WebServiceProject/wsdl/movie_service.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MOVIESERVICE_WSDL_LOCATION = url;
    }

    public MovieService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MovieService_Service() {
        super(MOVIESERVICE_WSDL_LOCATION, new QName("http://www.mycom.com/movie", "MovieService"));
    }

    /**
     * 
     * @return
     *     returns MovieService
     */
    @WebEndpoint(name = "MovieServiceSOAPPort")
    public MovieService getMovieServiceSOAPPort() {
        return super.getPort(new QName("http://www.mycom.com/movie", "MovieServiceSOAPPort"), MovieService.class);
    }

}
