
package com.webage.ejb;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "BadCustomerException", targetNamespace = "http://ejb.webage.com/")
public class BadCustomerException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BadCustomerException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BadCustomerException_Exception(String message, BadCustomerException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public BadCustomerException_Exception(String message, BadCustomerException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.webage.ejb.BadCustomerException
     */
    public BadCustomerException getFaultInfo() {
        return faultInfo;
    }

}
