
package com.webage.ejb;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Order", targetNamespace = "http://ejb.webage.com/")
public interface Order {


    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.webage.ejb.OrderSoupResponse>
     */
    @WebMethod(operationName = "orderSoup")
    @RequestWrapper(localName = "orderSoup", targetNamespace = "http://ejb.webage.com/", className = "com.webage.ejb.OrderSoup")
    @ResponseWrapper(localName = "orderSoupResponse", targetNamespace = "http://ejb.webage.com/", className = "com.webage.ejb.OrderSoupResponse")
    public Response<OrderSoupResponse> orderSoupAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param asyncHandler
     * @param arg0
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "orderSoup")
    @RequestWrapper(localName = "orderSoup", targetNamespace = "http://ejb.webage.com/", className = "com.webage.ejb.OrderSoup")
    @ResponseWrapper(localName = "orderSoupResponse", targetNamespace = "http://ejb.webage.com/", className = "com.webage.ejb.OrderSoupResponse")
    public Future<?> orderSoupAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<OrderSoupResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws BadCustomerException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "orderSoup", targetNamespace = "http://ejb.webage.com/", className = "com.webage.ejb.OrderSoup")
    @ResponseWrapper(localName = "orderSoupResponse", targetNamespace = "http://ejb.webage.com/", className = "com.webage.ejb.OrderSoupResponse")
    public String orderSoup(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws BadCustomerException_Exception
    ;

}
