
package com.webage.ejb;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "OrderBeanService", targetNamespace = "http://ejb.webage.com/", wsdlLocation = "file:/C:/workspace/EJBSvcWeb/OrderBean.wsdl")
public class OrderBeanService
    extends Service
{

    private final static URL ORDERBEANSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.webage.ejb.OrderBeanService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.webage.ejb.OrderBeanService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/workspace/EJBSvcWeb/OrderBean.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/workspace/EJBSvcWeb/OrderBean.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ORDERBEANSERVICE_WSDL_LOCATION = url;
    }

    public OrderBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderBeanService() {
        super(ORDERBEANSERVICE_WSDL_LOCATION, new QName("http://ejb.webage.com/", "OrderBeanService"));
    }

    /**
     * 
     * @return
     *     returns Order
     */
    @WebEndpoint(name = "OrderBeanPort")
    public Order getOrderBeanPort() {
        return super.getPort(new QName("http://ejb.webage.com/", "OrderBeanPort"), Order.class);
    }

}
