
package com.webage.warehouse;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "WarehouseSystemService", targetNamespace = "http://warehouse.webage.com/", wsdlLocation = "file:/C:/workspace/WSRMClientWeb/WarehouseService.wsdl")
public class WarehouseSystemService
    extends Service
{

    private final static URL WAREHOUSESYSTEMSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.webage.warehouse.WarehouseSystemService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.webage.warehouse.WarehouseSystemService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/workspace/WSRMClientWeb/WarehouseService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/workspace/WSRMClientWeb/WarehouseService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WAREHOUSESYSTEMSERVICE_WSDL_LOCATION = url;
    }

    public WarehouseSystemService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WarehouseSystemService() {
        super(WAREHOUSESYSTEMSERVICE_WSDL_LOCATION, new QName("http://warehouse.webage.com/", "WarehouseSystemService"));
    }

    /**
     * 
     * @return
     *     returns WarehouseSystem
     */
    @WebEndpoint(name = "WarehouseSystemPort")
    public WarehouseSystem getWarehouseSystemPort() {
        return super.getPort(new QName("http://warehouse.webage.com/", "WarehouseSystemPort"), WarehouseSystem.class);
    }

}
