
package com.webage.warehouse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WarehouseSystem", targetNamespace = "http://warehouse.webage.com/")
public interface WarehouseSystem {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createOrder", targetNamespace = "http://warehouse.webage.com/", className = "com.webage.warehouse.CreateOrder")
    @ResponseWrapper(localName = "createOrderResponse", targetNamespace = "http://warehouse.webage.com/", className = "com.webage.warehouse.CreateOrderResponse")
    public void createOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrderStatus", targetNamespace = "http://warehouse.webage.com/", className = "com.webage.warehouse.GetOrderStatus")
    @ResponseWrapper(localName = "getOrderStatusResponse", targetNamespace = "http://warehouse.webage.com/", className = "com.webage.warehouse.GetOrderStatusResponse")
    public String getOrderStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
